version: '3'

services:
  master:
    build: ./jmeter-master
    container_name: jmeter-master
    tty: true # tty true make the docker image stay up even with nothing running
    networks:
      - monitor-network

  slave:
    build: ./jmeter-slave
    networks:
      - monitor-network

  influxdb:
    build: ./influxdb
    container_name: influxdb
    ports:
      - "9086:8086"
    networks:
      - monitor-network
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  chronograf:
    build: ./chronograf
    container_name: chronograf
    ports:
      - "9088:8888"
    networks:
      - monitor-network
    links:
      - influxdb
    volumes:
      - ./data/chronograf:/var/lib/chronograf

  kapacitor:
    build: ./kapacitor
    container_name: kapacitor
    ports:
      - "9092:9092"
    networks:
      - monitor-network
    links:
      - influxdb
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor

  grafana:
    build: ./grafana
    container_name: grafana
    restart: always
    ports: 
      - "9001:3000"
    networks:
      - monitor-network
    links:
      - influxdb

networks:
  monitor-network:
    driver: bridge


