version: '3'

services:
  master:
    build: ./jmeter-master
    container_name: jmeter-master
    tty: true # tty true make the docker image stay up even with nothing running
    networks:
      - jmeter-network
  slave:
    build: ./jmeter-slave
    networks:
      - jmeter-network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "9003:2003"
      - "9083:8083"
      - "9086:8086"
      - "9090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_GRAPHITE_ENABLED: 1
      INFLUXDB_REPORTING_DISABLED: 0
      ADMIN_USER: root
      INFLUXDB_INIT_PWD: 1nfluxDB
      PRE_CREATE_DB: jmeter
    networks:
      - jmeter-network
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - "./data/influxdb:/var/lib/influxdb"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports: 
      - "9001:3000"
      - "9200:9200"
    environment:
      GF_SERVER_ROOT_URL: http://127.0.0.1
      GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge


